### ISSUE TITLE
Can just the "manual" directory be cloned and updated with each commit?

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#21] opened 2021-08-30 02:22 UTC
Alec, could you just copy the individual <plugiin>/manual/  to opencpn-manuals/plugins?

I think that would be much better and clearer abbout intent.

**Comment by rgleason** [comment] 2021-08-30 02:46
Now I think that is what is being done. Sorry for the static.

**Comment by rgleason** [comment] 2021-08-30 11:50
I guess I was wrong.  Why duplicate entire contents of each plugin, when all that is needed is the "manual"?

This is only a ONE WAY process is it not?    Any Edits are done on the Dev' repository, not on this?  Ressulting in a PR the Dev then accepts.

**Comment by leamas** [comment] 2021-08-30 11:54
What is the issue here, exactly?

**Comment by rgleason** [comment] 2021-08-30 11:57
You've duplicated the entire content of each plugin repos.  Just dupllicate "manual" as it says above.

**Comment by leamas** [comment] 2021-08-30 11:59
Patches welcome. That said, when you use `./source-state.sh restore` your claim is wrong.

**Comment by rgleason** [comment] 2021-08-30 12:07
Are you going to need the full plugin code in opencpn-manuals in order to package and include documentation with the code going to cloudsmith for example?

**Comment by leamas** [comment] 2021-08-30 12:28
If we would upload anything to cloudsmith it would be the HTML documents, and only those, I guess.

The word "packaging" in this context usually refers to making something (usually, but not always compiled code) available as package a user can install. Here, it's required that one can build the HTML from sources, and your statement makes some minimal sense.

However, in order to build the docs you don't need to include any plugins at all, not even the manual/ directory. The only thing needed is sources.state since it is possible to re-create everything required from that. 

This is also what the automated build does.  It starts with an empty sources/ directory and populates it with evertything needed  as defined by sources .state before building

**Comment by rgleason** [comment] 2021-08-30 12:34
`..and your statement makes some minimal sense.
`Thanks, 

`in order to build the docs you don't need to include any plugins at all, not even the manual/ directory. The only thing needed is sources.state since it is possible to re-create everything required from that.`

Ok, so why are there cloned or forked plugin repositories in  opencpn-manuals?

https://github.com/opencpn-manuals/celestial_navigation_pi

**Comment by leamas** [comment] 2021-08-30 13:59
They are not part of the git repo, but still required to build the docs. That is, when you clone plugins/ you get an empty sources directory.

**Comment by rgleason** [comment] 2021-08-30 14:10
They are in the opencpn-manuals as repositories that have been cloned or forked, but they are needed to build plugins because retrieving from distribured pi repos takes too long?

**Comment by leamas** [comment] 2021-08-30 14:17
The are required because Antora must have all files available when building the docs.

Without the source-state.sh mechanics antora caches  retrieved repos. To clone them every time would be too slow.

Compared to the antora cache source-state.sh gives us two advantages:

  - A possibility to recreate the same build by re-creating exactly the same cache (i. e., sources) dir.
  - That we only clone the required stuff, not the complete repo.

**Comment by leamas** [comment] 2021-08-31 05:31
Reading this confused mess again, I see: 

> They are in the opencpn-manuals as repositories that have been cloned or forked

They are **not** in in the opencpn-manuals as repositories that have been cloned or forked. Cloning opencpn-manuals/plugins gives an empty _sources_ directory. This way we avoid having a too large git repo full of duplicates.

OTOH, we need them in place to actually make the build. This is done by source-state.sh. `source-state.sh restore`  clones everything required using  a defined commit.

**Comment by leamas** [comment] 2021-08-31 09:12
I'm tempted to close this. I don't really understand what the issue is about. The initial question (and questions are not issues) is dead, and the next (the complete contents of repos in sources is cloned) is plain wrong.  Dunno what's left.

**Comment by rgleason** [comment] 2021-08-31 21:05
I do not believe that is the full explanation of how the scripts and system works. I believe that such an explanation is needed for new devs.  

Sorry if it confused. Perhaps someone in the know can provide such an overview.

**Comment by leamas** [comment] 2021-08-31 21:10
Now you are talking about an overview.

 Again: What is this issue about?

**Closed as completed** 2021-08-31 21:45 UTC
