### ISSUE TITLE
Edit this Page  removed for opencpn-manual/plugins ?

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#47] opened 2021-09-16 18:05 UTC
See 
https://github.com/opencpn-manuals/plugins/pull/44#issuecomment-921063326

Perhaps we should have a note in
Workflow?

**Comment by leamas** [comment] 2021-09-16 21:52
Duplicate of #48. Closing

**Closed as completed by leamas** 2021-09-16 21:52 UTC
